site_name: Tienda Velas Ignia Docs
nav:
  - Inicio: 00-index.md
  - Introducción: 01-introduccion.md
  - Instalación: 02-instalacion.md
  - Uso: 03-uso.md
  - Arquitectura: 04-arquitectura.md
  - Conclusiones: 05-conclusiones.md
  - Referencias: 06-referencias.md
theme: readthedocs
